defmodule Orcasite.Repo.Migrations.AddActiveToNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notifications) do
      remove :processed_at

      add :active, :boolean, default: true
    end
  end

  def down do
    alter table(:notifications) do
      remove :active
      add :processed_at, :utc_datetime_usec
    end
  end
end
