defmodule Orcasite.Repo.Migrations.AddTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create unique_index(:subscriptions, [:id], name: "subscriptions_id_index")
  end

  def down do
    drop_if_exists unique_index(:subscriptions, [:id], name: "subscriptions_id_index")

    drop table(:tokens)
  end
end