defmodule Orcasite.Repo.Migrations.CreateNotificationSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subscriptions, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true, default: fragment("uuid_generate_v4()")
      add :name, :text
      add :meta, :map
      add :event_type, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :subscriber_id, :uuid
    end

    create table(:subscription_notifications, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true, default: fragment("uuid_generate_v4()")
      add :processed_at, :utc_datetime_usec
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :subscription_id,
          references(:subscriptions,
            column: :id,
            name: "subscription_notifications_subscription_id_fkey",
            type: :uuid
          )

      add :notification_id, :uuid
    end

    create table(:subscribers, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true, default: fragment("uuid_generate_v4()")
    end

    alter table(:subscriptions) do
      modify :subscriber_id,
             references(:subscribers,
               column: :id,
               name: "subscriptions_subscriber_id_fkey",
               type: :uuid
             )
    end

    alter table(:subscribers) do
      add :name, :text
      add :subscriber_type, :text
      add :meta, :map
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true, default: fragment("uuid_generate_v4()")
    end

    alter table(:subscription_notifications) do
      modify :notification_id,
             references(:notifications,
               column: :id,
               name: "subscription_notifications_notification_id_fkey",
               type: :uuid
             )
    end

    alter table(:notifications) do
      add :meta, :map
      add :processed_at, :utc_datetime_usec
      add :event_type, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:notifications) do
      remove :updated_at
      remove :inserted_at
      remove :event_type
      remove :processed_at
      remove :meta
    end

    drop constraint(
           :subscription_notifications,
           "subscription_notifications_notification_id_fkey"
         )

    alter table(:subscription_notifications) do
      modify :notification_id, :uuid
    end

    drop table(:notifications)

    alter table(:subscribers) do
      remove :updated_at
      remove :inserted_at
      remove :meta
      remove :subscriber_type
      remove :name
    end

    drop constraint(:subscriptions, "subscriptions_subscriber_id_fkey")

    alter table(:subscriptions) do
      modify :subscriber_id, :uuid
    end

    drop table(:subscribers)

    drop constraint(
           :subscription_notifications,
           "subscription_notifications_subscription_id_fkey"
         )

    drop table(:subscription_notifications)

    drop table(:subscriptions)
  end
end
