defmodule Orcasite.Repo.Migrations.AddActiveToNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notifications) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :processed_at

      add :active, :boolean, default: true
    end
  end

  def down do
    alter table(:notifications) do
      remove :active
      # This is the `down` migration of the statement:
      #
      #     remove :processed_at
      #

      # add :processed_at, :utc_datetime_usec
    end
  end
end