defmodule Orcasite.Repo.Migrations.AddSlugIndexToFeeds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feeds) do
      modify :name, :text
      modify :node_name, :text
      modify :slug, :text
      modify :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      modify :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:feeds, [:slug], name: "feeds_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:feeds, [:slug], name: "feeds_unique_slug_index")
  end
end
