defmodule Orcasite.Repo.Migrations.MakeLocationPointNonNil do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feeds) do
      modify :location_point, :geometry, null: false
    end
  end

  def down do
    alter table(:feeds) do
      modify :location_point, :geometry, null: true
    end
  end
end