defmodule Orcasite.Repo.Migrations.AddVisibleToFeeds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feeds) do
      add :visible, :boolean, default: true
    end
  end

  def down do
    alter table(:feeds) do
      remove :visible
    end
  end
end