defmodule Orcasite.Repo.Migrations.MakeFeedAttrsNonNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feeds) do
      modify :slug, :text, null: false
      modify :node_name, :text, null: false
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:feeds) do
      modify :name, :text, null: true
      modify :node_name, :text, null: true
      modify :slug, :text, null: true
    end
  end
end