defmodule Orcasite.Repo.Migrations.UpdateDetectionCategoryFromOrcaToWhale do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("update detections set category = 'whale' where category = 'orca'")
  end

  def down do
    execute("update detections set category = 'orca' where category = 'whale'")
  end
end
