defmodule Orcasite.Repo.Migrations.AddObanTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    Oban.Migration.up(version: 11)
    alter table(:subscription_notifications) do
      modify :status, :text, default: "new"
    end
  end

  def down do
    alter table(:subscription_notifications) do
      modify :status, :text, default: "pending"
    end
    Oban.Migration.up(version: 1)
  end
end
