defmodule Orcasite.Repo.Migrations.AddIntroHtmlToFeeds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feeds) do
      add :intro_html, :text, default: ""
    end
  end

  def down do
    alter table(:feeds) do
      remove :intro_html
    end
  end
end
