defmodule Orcasite.Repo.Migrations.UpdateNonNullCandidatesAttrs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:candidates) do
      modify :feed_id, :uuid, null: false
      modify :max_time, :utc_datetime_usec, null: false
      modify :min_time, :utc_datetime_usec, null: false
    end
  end

  def down do
    alter table(:candidates) do
      modify :min_time, :utc_datetime_usec, null: true
      modify :max_time, :utc_datetime_usec, null: true
      modify :feed_id, :uuid, null: true
    end
  end
end
