defmodule Orcasite.Repo.Migrations.AddCategoryToCandidate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:detections, [:category])

    alter table(:candidates) do
      add :category, :text
    end

    create index(:candidates, [:category])
  end

  def down do
    drop_if_exists index(:candidates, [:category])

    alter table(:candidates) do
      remove :category
    end

    drop_if_exists index(:detections, [:category])
  end
end
