defmodule Orcasite.Repo.Migrations.AddLastErrorToAudioImage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:audio_images) do
      modify :feed_id, :uuid, null: false
      modify :end_time, :utc_datetime_usec, null: false
      modify :start_time, :utc_datetime_usec, null: false
      modify :status, :text, null: false
      add :last_error, :text
    end
  end

  def down do
    alter table(:audio_images) do
      remove :last_error
      modify :status, :text, null: true
      modify :start_time, :utc_datetime_usec, null: true
      modify :end_time, :utc_datetime_usec, null: true
      modify :feed_id, :uuid, null: true
    end
  end
end
