defmodule Orcasite.Repo.Migrations.AddUniqueIndexToAudioImage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:audio_images, [:feed_id, :image_type, :start_time, :end_time],
             name: "audio_images_unique_audio_image_index"
           )
  end

  def down do
    drop_if_exists unique_index(:audio_images, [:feed_id, :image_type, :start_time, :end_time],
                     name: "audio_images_unique_audio_image_index"
                   )
  end
end
