defmodule Orcasite.Repo.Migrations.AddCategoryToCandidate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:detections) do
      modify :category, :text, null: false
    end

    alter table(:candidates) do
      add :category, :text
    end
  end

  def down do
    alter table(:candidates) do
      remove :category
    end

    alter table(:detections) do
      modify :category, :text, null: true
    end
  end
end
