defmodule Orcasite.Repo.Migrations.UpdateUserAdminAndModDefaultFalse do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "update users set admin = 'f' where admin is null;"
    execute "update users set moderator = 'f' where moderator is null;"

    flush()

    alter table(:users) do
      modify :moderator, :boolean, null: false, default: false
      modify :admin, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:users) do
      modify :admin, :boolean, null: true, default: nil
      modify :moderator, :boolean, null: true, default: nil
    end
  end
end
