defmodule Orcasite.Repo.Migrations.AddTrackingToNotifications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:notifications) do
      add :target_count, :bigint
      add :notified_count, :bigint, default: 0
      add :notified_count_updated_at, :utc_datetime
    end
  end

  def down do
    alter table(:notifications) do
      remove :notified_count_updated_at
      remove :notified_count
      remove :target_count
    end
  end
end
