defmodule Orcasite.Repo.Migrations.UpdateAudioImageFeedSegmentJoinTableUnique do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:audio_image_feed_segments, [:feed_segment_id, :audio_image_id],
             name: "audio_image_feed_segments_unique_audio_image_index"
           )
  end

  def down do
    drop_if_exists unique_index(:audio_image_feed_segments, [:feed_segment_id, :audio_image_id],
                     name: "audio_image_feed_segments_unique_audio_image_index"
                   )
  end
end
