defmodule Orcasite.Repo.Migrations.AddOrcahelloIdToFeeds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feeds) do
      add :orcahello_id, :text
    end

    create index(:feeds, [:orcahello_id])
  end

  def down do
    drop_if_exists index(:feeds, [:orcahello_id])

    alter table(:feeds) do
      remove :orcahello_id
    end
  end
end
