defmodule Orcasite.Repo.Migrations.UpdateStartTimeNonNullInBouts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bouts) do
      remove :ongoing
      modify :category, :text, null: false
      modify :start_time, :utc_datetime_usec, null: false
    end
  end

  def down do
    alter table(:bouts) do
      modify :start_time, :utc_datetime_usec, null: true
      modify :category, :text, null: true
      add :ongoing, :boolean
    end
  end
end
