defmodule Orcasite.Repo.Migrations.AddIdIdentitiesForSeedUpserts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:detections, [:id], name: "detections_id_index")

    create unique_index(:candidates, [:id], name: "candidates_id_index")

    create unique_index(:audio_images, [:id], name: "audio_images_id_index")
  end

  def down do
    drop_if_exists unique_index(:audio_images, [:id], name: "audio_images_id_index")

    drop_if_exists unique_index(:candidates, [:id], name: "candidates_id_index")

    drop_if_exists unique_index(:detections, [:id], name: "detections_id_index")
  end
end
