defmodule Orcasite.Repo.Migrations.AddUniqueTagToItemTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:item_tags, [:user_id, :tag_id, :bout_id],
             name: "item_tags_unique_tag_index"
           )
  end

  def down do
    drop_if_exists unique_index(:item_tags, [:user_id, :tag_id, :bout_id],
                     name: "item_tags_unique_tag_index"
                   )
  end
end
