defmodule Orcasite.Repo.Migrations.AddNameToBouts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:bouts) do
      add :name, :text
    end
  end

  def down do
    alter table(:bouts) do
      remove :name
    end
  end
end
