defmodule Orcasite.Repo.Migrations.AddMaintainerEmailsToFeeds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feeds) do
      add :maintainer_emails, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:feeds) do
      remove :maintainer_emails
    end
  end
end
