defmodule Orcasite.Repo.Migrations.AddDetectionBotToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :detection_bot, :boolean, null: false, default: false
    end

    create_if_not_exists unique_index(:detections, [:id], name: "detections_id_index")
  end

  def down do
    drop_if_exists unique_index(:detections, [:id], name: "detections_id_index")

    alter table(:users) do
      remove :detection_bot
    end
  end
end
