defmodule Orcasite.Repo.Migrations.AddIdempotencyKeyToDetections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:detections) do
      add :idempotency_key, :text
    end

    create unique_index(:detections, [:idempotency_key], name: "detections_idempotency_key_index")
  end

  def down do
    drop_if_exists unique_index(:detections, [:idempotency_key],
                     name: "detections_idempotency_key_index"
                   )

    alter table(:detections) do
      remove :idempotency_key
    end
  end
end
