defmodule Orcasite.Repo.Migrations.AddNameIndexToTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:tags, [:name])

    create index(:tags, ["name gin_trgm_ops"], name: "tags_name_gin_index", using: "gin")
  end

  def down do
    drop_if_exists index(:tags, ["name gin_trgm_ops"], name: "tags_name_gin_index")

    create index(:tags, [:name], using: "gin")
  end
end
