defmodule Orcasite.Repo.Migrations.AddCertaintyToItemTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:item_tags) do
      add :certainty, :text
    end
  end

  def down do
    alter table(:item_tags) do
      remove :certainty
    end
  end
end
