defmodule Orcasite.Repo.Migrations.AddKindAndIriToTags do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tags) do
      add :kind, :text
      add :iri, :text
    end

    create index(:tags, ["lower(name)"], name: "tags_lower_name_index", unique: true)

    create unique_index(:tags, [:iri], name: "tags_unique_iri_index")
  end

  def down do
    drop_if_exists unique_index(:tags, [:iri], name: "tags_unique_iri_index")

    drop_if_exists index(:tags, ["lower(name)"], name: "tags_lower_name_index")

    alter table(:tags) do
      remove :iri
      remove :kind
    end
  end
end
