defmodule Orcasite.Repo.Migrations.AddProgramDateTimeToFeedSegments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:feed_segments) do
      add :program_date_time, :utc_datetime_usec
    end
  end

  def down do
    alter table(:feed_segments) do
      remove :program_date_time
    end
  end
end
