use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# OrcasiteWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :orcasite, OrcasiteWeb.Endpoint,
  load_from_system_env: true,
  url: [scheme: "https", host: System.get_env("HOST_URL"), port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Configure your database
#config :orcasite, Orcasite.Repo,
#  adapter: Ecto.Adapters.Postgres,
#  url: System.get_env("DATABASE_URL"),
#  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
#  ssl: true,
#  types: Orcasite.PostgresTypes

config :orcasite, Orcasite.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "jlcguunigrjccb", # System.get_env("POSTGRES_USER") || "postgres",
  password: "dadcdb4491a1885281207bdd1599941cfca2ce0cde8fb637a79a629894a6efc1", # System.get_env("POSTGRES_PASSWORD") || "postgres",
  database: "d20alaqc47mce9", # System.get_env("POSTGRES_DATABASE") || "orcasite_dev",
  hostname: "ec2-50-16-196-138.compute-1.amazonaws.com", # System.get_env("POSTGRES_HOST") || "localhost",
  port: 5432, # System.get_env("POSTGRES_PORT") || 5432,
  pool_size: 1,
  ssl: true,
  types: Orcasite.PostgresTypes


# Do not print debug messages in production
# config :logger, level: :info, format: {Orcasite.Logger, :format}

config :orcasite, :orcasite_s3_url, "https://s3-us-west-2.amazonaws.com/orcasite" #System.get_env("ORCASITE_S3_URL")

#config :orcasite, OrcasiteWeb.Guardian,
#  issuer: "orcasite",
#  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"
