name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build --build-arg MIX_ENV=test

      - name: Start containers
        run: docker compose up -d db cache

      - name: Run tests
        run: docker compose run web bash -c 'cd server && mix test'
