name: Merge validation

on:
  pull_request:
    branches:
      - "prod"
      - "stage"

jobs:
  merge-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Merge validation
        run: |
          echo "This branch only accepts fast forward merges. To merge this PR, leave a comment with the /fast-forward command"
          exit 1
